package enums

import "fmt"

type PokemonType uint8

// generated by claude :3

const (
	NORMAL   PokemonType = iota // 0
	FIGHTING                    // 1
	FLYING                      // 2
	POISON                      // 3
	GROUND                      // 4
	ROCK                        // 5
	BUG                         // 6
	GHOST                       // 7
	STEEL                       // 8
	FIRE                        // 9
	WATER                       // 10
	GRASS                       // 11
	ELECTRIC                    // 12
	PSYCHIC                     // 13
	ICE                         // 14
	DRAGON                      // 15
	DARK                        // 16
	UNKNOWN                     // 17 - "???" type
)

// TypeName returns the string representation of a type ID
func (pt PokemonType) String() string {
	typeNames := map[PokemonType]string{
		NORMAL:   "Normal",
		FIGHTING: "Fighting",
		FLYING:   "Flying",
		POISON:   "Poison",
		GROUND:   "Ground",
		ROCK:     "Rock",
		BUG:      "Bug",
		GHOST:    "Ghost",
		STEEL:    "Steel",
		FIRE:     "Fire",
		WATER:    "Water",
		GRASS:    "Grass",
		ELECTRIC: "Electric",
		PSYCHIC:  "Psychic",
		ICE:      "Ice",
		DRAGON:   "Dragon",
		DARK:     "Dark",
		UNKNOWN:  "???",
	}

	if name, ok := typeNames[pt]; ok {
		return name
	}
	
	return fmt.Sprintf("Invalid(%d)", pt)
}